### ISSUE TITLE
Drop Python 3.6 support 

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/quacks#12]
Python 3.6 is EOL [next week](https://endoflife.date/python).

Removing support for Python 3.6 is quite nice:
- no need for `dataclasses` backport
- no need for special `ClassVar` detection and the coverage exemptions it requires

Mentions of 3.6 need to be removed from tox, github build, pyproject.toml

**Comment by exoriente** [comment]
Hi @ariebovenberg , I'd love to pick this up! Can you assign this issue to me or authorize me to assign myself?

**Comment by ariebovenberg** [comment]
@exoriente done!

**Comment by ariebovenberg** [comment]
Thanks for solving. It's just been released in version 0.2.0
